type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 127.0.0.1:6002
  password: '123456'

knex:
  client: 'sqlite3'
  connection:
    filename: 'db.sqlite'
  useNullAsDefault: true

logger:
  init:
    level: fatal
  process:
    level: fatal
