type: s

shadowsocks:
  host: 127.0.0.1
  port: 6001

listen:
  host: 0.0.0.0
  port: 6002
  password: '123456'

knex:
  client: 'sqlite3'
  connection:
    filename: 'db.sqlite'
  useNullAsDefault: true

logger:
  init:
    level: fatal
  process:
    level: fatal
